{"name": "test_add_group[None:name2:header2:footer2]", "status": "broken", "statusDetails": {"message": "AttributeError: module 'pytest' has no attribute 'allure'", "trace": "app = <fixture.application.Application object at 0x0000026CAC032060>\ndb = <fixture.db.DbFixture object at 0x0000026CABFDE360>, data_groups = None:name2:header2:footer2, check_ui = False\n\n    def test_add_group(app, db, data_groups, check_ui):\n        group = data_groups\n>       with pytest.allure.step('Given a group list'):\nE       AttributeError: module 'pytest' has no attribute 'allure'\n\ntest\\test_add_group.py:28: AttributeError"}, "parameters": [{"name": "data_groups", "value": "None:name2:header2:footer2"}], "start": 1731427396276, "stop": 1731427396276, "uuid": "511098ca-51c9-40cd-b54a-dd63af345990", "historyId": "1ece1d6d96d9e943edf5a7f2035be7f3", "testCaseId": "8e9b1d07ef6cdb67de3c4a3d82e10652", "fullName": "test.test_add_group#test_add_group", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_add_group"}, {"name": "host", "value": "LAPTOP-R1K1EE83"}, {"name": "thread", "value": "31444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_add_group"}]}