{"name": "test_add_group[None:name1:header1:footer1]", "status": "broken", "statusDetails": {"message": "AttributeError: module 'pytest' has no attribute 'allure'", "trace": "app = <fixture.application.Application object at 0x0000026CAC032060>\ndb = <fixture.db.DbFixture object at 0x0000026CABFDE360>, data_groups = None:name1:header1:footer1, check_ui = False\n\n    def test_add_group(app, db, data_groups, check_ui):\n        group = data_groups\n>       with pytest.allure.step('Given a group list'):\nE       AttributeError: module 'pytest' has no attribute 'allure'\n\ntest\\test_add_group.py:28: AttributeError"}, "parameters": [{"name": "data_groups", "value": "None:name1:header1:footer1"}], "start": 1731427395041, "stop": 1731427395042, "uuid": "8d81298f-f033-4661-81ab-63b4cac19f74", "historyId": "fab3b9757800c2e8f3b737237518f6d4", "testCaseId": "8e9b1d07ef6cdb67de3c4a3d82e10652", "fullName": "test.test_add_group#test_add_group", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_add_group"}, {"name": "host", "value": "LAPTOP-R1K1EE83"}, {"name": "thread", "value": "31444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_add_group"}]}