{"name": "test_add_group[None:name3:header3:footer3]", "status": "broken", "statusDetails": {"message": "AttributeError: module 'pytest' has no attribute 'allure'", "trace": "app = <fixture.application.Application object at 0x0000026CAC032060>\ndb = <fixture.db.DbFixture object at 0x0000026CABFDE360>, data_groups = None:name3:header3:footer3, check_ui = False\n\n    def test_add_group(app, db, data_groups, check_ui):\n        group = data_groups\n>       with pytest.allure.step('Given a group list'):\nE       AttributeError: module 'pytest' has no attribute 'allure'\n\ntest\\test_add_group.py:28: AttributeError"}, "parameters": [{"name": "data_groups", "value": "None:name3:header3:footer3"}], "start": 1731427397258, "stop": 1731427397258, "uuid": "544b831c-810b-4c2d-8509-495e5a460f6b", "historyId": "2fb2cf31378e2e2d0cd54553e9418bae", "testCaseId": "8e9b1d07ef6cdb67de3c4a3d82e10652", "fullName": "test.test_add_group#test_add_group", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_add_group"}, {"name": "host", "value": "LAPTOP-R1K1EE83"}, {"name": "thread", "value": "31444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_add_group"}]}